# Use a more recent Rust image as the base image
FROM rust:latest as builder

# Set the working directory
WORKDIR /app

# Copy the entire project
COPY . .

# Build the project
RUN cargo build --release

# Use a smaller image for runtime
FROM debian:bookworm-slim

# Install required dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# Copy the binary from the builder stage
COPY --from=builder /app/target/release/backend-rust /usr/local/bin/
COPY --from=builder /app/products.json .

# Set the entrypoint
ENTRYPOINT ["/usr/local/bin/backend-rust"]

# Expose the port
EXPOSE 5000
